### ISSUE TITLE
Error using custom weights

### ISSUE THREAD

**Issue by ldan29** [khliland/EMSC#6]
Hi,

I have an issue when using custom weights for the EMSC algorithm. Depending on the degree chosen, I get either "Longer object length is not a multiple of shorter object length" or dims [product xxxx] do not match the length of object [xxxx]"

The issue seems to be at line 15 :

`    modelw <- model$model * rep(model$weights, each = n)
`

I am not sure why the "n" variable is needed here, it doesn't match with the dimensions of the object "model". I know of the objectives of using EMSC but I am less familiar with the maths behind it.

Best regards,
Lucas

**Comment by khliland** [comment]
Thanks Lucas,

This is an error that has lived with the package since its inception. I pushed an update here to GitHub now (installable with devtools) and will upload it to CRAN soon.

Regards,
Kristian

**Comment by ldan29** [comment]
Thanks,

Just tried it using devtools, no more error ! However I still have a doubt about the results.
Basically when using weights, the corrected spectras actually looks a lot like my weights vector. I would expect it to look more like my reference spectra (which is the mean of all my spectras), like with a classical MSC or even an SNV, albeit a bit different because of the weights of course.

I am not sure that this could be the solution, but again at line 15, I saw that the "model" object contains the reference spectra, is it normal that the weights are also applied to that ? 

As I said, I'm not entirely sure of the maths behind the EMSC, I only understand the principle and utility behind it so feel free to correct me if my assumptions are wrong !

**Comment by khliland** [comment]
Hi Lucas,

The times I have seen weighting applied with EMSC it has mainly been used for practically zeroing out regions of spectra that are deemed too noisy, unstable or have no chemical relevance to the problem at hand. In these cases, we have used a constant vector of weights, e.g., rep(1, n.variables) and then modified the weights to be very small, e.g., 10^-12 for unwanted regions. Through this, we can retain the shape of the spectra and have polynomials following the original wavelengths/wavenumbers of the spectra, but still focusing on the stable and interesting parts. In the MATLAB implementations I have access to from the first days of EMSC, the mathematics is simply to element-wise multiply the spectra and model with the weights. If the reference spectrum is far from zero or of very low magnitude, then I suppose the weights may dominate.

An option could be to have a parameter controlling if the reference spectrum should be left out of the weighting, or if only the data, not the model should be weighted. Would it be interesting to test such an implementation?

**Comment by ldan29** [comment]
Hi,

Sorry for the very late answer. I think there is no need to spend time implementing such an option, unless you have more demand for it. I have no immediate need for that and was trying it out of curiosity on my data. I think in any case, I could edit the function locally using trace() to leave what I want out of the weighting.

Thanks again for your help.
